### ISSUE TITLE
Focus request issue 

### ISSUE THREAD

**Issue by Suret1** [logomount/the-movie#1]

**Comment by Suret1** [comment]
![Screenshot_2024-11-04-13-02-23-451_com miui bugreport](https://github.com/user-attachments/assets/a46a9b34-fb4f-400f-ad3e-2f236f2a32e0)

**Comment by logomount** [comment]
@Suret1 Thank you for catching this! I've replaced `LifecycleResumeEffect` with `LaunchedEffect`, I think this should fix the issue. Could you have a try and let me know if it's fixed :)

**Comment by Suret1** [comment]
> @Suret1 Thank you for catching this! I've replaced `LifecycleResumeEffect` with `LaunchedEffect`, I think this should fix the issue. Could you have a try and let me know if it's fixed :) 

I'll test it and give feedback

**Comment by Suret1** [comment]
I did the test and the problem persists.

**Comment by logomount** [comment]
@Suret1 Thank you for the video - that was really helpful! The issue was that if you scroll down, navigate to another screen and come back, the first item was not visible and focus requester not attached. I've moved LaunchedEffect inside the item of LazyColumn and it seems to be finally working correct :)

**Comment by Suret1** [comment]
You're welcome. It was a good experience for me too.
